

import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "../../components/AppWalletProvider";

// Load custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Well Fit",
  description: "Generated by create next app",
};

// Function to generate static params for supported languages
export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }];
}

// Root layout component with dynamic localization based on language parameter
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: 'en-US' | 'de' | 'de-ES' }>;
}>) {
  // Resolve the language from params and pass it to the HTML tag
  const { lang } = await params;

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWalletProvider>{children}</AppWalletProvider>
      </body>
    </html>
  );
}
